-- 这段代码是 cfg_sector_lte_refactor 中从itg原始表中取出来的小区经纬度 , 这是其中的一段代码
-- 直接来源于 : itg_cm_lte_sit_d , itg_cm_lte_enb_d , itg_cm_lte_cel_d , itg_cm_lte_ant_d , itg_cm_lte_rru_d , itg_cm_lte_room_d

cache TABLE cfg_sector_lte_refactor_temp AS
SELECT  concat(enb_id,'_',cel_id)                                                                               AS oid
       ,CASE WHEN cover_type = 2 AND abs(roomlon) > 0 THEN cast(roomlon AS decimal(20,8))
             WHEN antlon > '' THEN cast(antlon AS decimal(20,8))
             WHEN rrulon > '' THEN cast(rrulon AS decimal(20,8))
             WHEN enodeblon > '' THEN cast(enodeblon AS decimal(20,8))
             ELSE cast(sitelon AS decimal(20,8))   END                                                          AS celllon
       ,CASE WHEN cover_type = 2 AND abs(roomlat) > 0 THEN cast(roomlat AS decimal(20,8))
             WHEN antlat > '' THEN cast(antlat AS decimal(20,8))
             WHEN rrulat > '' THEN cast(rrulat AS decimal(20,8))
             WHEN enodeblat > '' THEN cast(enodeblat AS decimal(20,8))
             ELSE cast(sitelat AS decimal(20,8))   END                                                          AS celllat

FROM
(
    -- Generated By AI Start (Cursor)
    SELECT  distinct enb_id
           ,cel_id
           ,sitelon
           ,enodeblon
           ,antlon
           ,rrulon
           ,roomlon
           ,sitelat
           ,enodeblat
           ,antlat
           ,rrulat
           ,roomlat
           ,cover_area_type
           ,cover_type
           ,row_number() over(distribute by enb_id,cel_id sort by cover_area_type desc) AS rank
    -- Generated By AI End (Cursor)
    FROM
    (
        SELECT  latitude  AS sitelat
               ,longitude AS sitelon
               ,sit_code
        FROM itg_cm_lte_sit_d
        WHERE p_provincecode = 330000
        -- Generated By AI Start (Cursor)
        AND p_date = '2026-03-25'
        -- Generated By AI End (Cursor)
    ) sit
    RIGHT JOIN
    (
        SELECT  city_id
               ,city_name
               ,CASE WHEN enb_id = 'null' THEN null  ELSE enb_id END    AS enb_id
               ,enb_type
               ,latitude                                                AS enodeblat
               ,longitude                                               AS enodeblon
               ,province_id
               ,region_id                                               AS enb_region_id
               ,region_name                                             AS enb_region_name
               ,related_sit_code
               ,(case WHEN vendor_id = '7' THEN '2' else vendor_id end) AS vendor_id
               ,(case WHEN vendor_name like '%中兴%' THEN 'ZTE'
                      WHEN vendor_name like '%华为%' THEN 'Huawei'
                      WHEN vendor_name like '%诺基亚%' THEN 'Nokia'
                      WHEN vendor_name like '%爱立信%' THEN 'Ericsson'
                      WHEN vendor_name like '%大唐%' THEN 'Datang'
                      WHEN vendor_name like '%贝尔%' THEN 'Beier'
                      WHEN vendor_name like '%烽火%' THEN 'Fenghuo'
                 else null end)                                         AS vendor_name
               ,regexp_replace(zh_label,",","&")                        AS zh_label
        FROM itg_cm_lte_enb_d
        WHERE p_provincecode = 330000
        -- Generated By AI Start (Cursor)
        AND p_date = '2026-03-25'
        -- Generated By AI End (Cursor)
        AND enb_id > ''
    ) enb
    ON sit.sit_code = enb.related_sit_code
    RIGHT JOIN
    (
        SELECT  explode(split((case when ant_code is null then '' else ant_code end),",")) AS ant_code
               ,eutraband
               ,cel_id
               ,cover_type
               ,dlfrequency
               ,dl_earfcn
               ,bandclass
               ,pci
               ,cel_region_id
               ,cel_region_name
               ,related_enb_id
               ,tac
               ,userlabel
               ,dlband
               ,ulband
               ,cel_code
               ,col_status
               ,room_code
        FROM
        (
            SELECT  ant_code
                   ,bandindicator                                                        AS eutraband
                   ,CASE WHEN cel_id = 'null' THEN null  ELSE cel_id END                 AS cel_id
                   ,cover_type
                   ,freq_dl                                                              AS dlfrequency
                   ,freq_pointno_dl                                                      AS dl_earfcn
                   ,case WHEN freq_pointno_dl >= 0    AND freq_pointno_dl <= 599 THEN '2.1G'
                         WHEN freq_pointno_dl >= 1200 AND freq_pointno_dl <= 1949 THEN '1.8G'
                         WHEN freq_pointno_dl >= 2400 AND freq_pointno_dl <= 2649 THEN '800M'
                    else 'Other' end                                                     AS bandclass
                   ,pci
                   ,region_id                                                            AS cel_region_id
                   ,region_name                                                          AS cel_region_name
                   ,CASE WHEN related_enb_id = 'null' THEN null  ELSE related_enb_id END AS related_enb_id
                   ,tac
                   ,regexp_replace(userlabel,",","&")                                    AS userlabel
                   ,bandwidth_dl                                                         AS dlband
                   ,bandwidth_ul                                                         AS ulband
                   ,cel_code
                   ,col_status
                   ,explode(split((case when room_code is null then '' else room_code end),","))                                        AS room_code
            FROM itg_cm_lte_cel_d
            WHERE p_provincecode = 330000
            -- Generated By AI Start (Cursor)
            AND p_date = '2026-03-25'
            -- Generated By AI End (Cursor)
            AND cel_id > ''
            AND related_enb_id > ''
        )
    ) cel
    ON cel.related_enb_id = enb.enb_id
    LEFT JOIN
    (
        SELECT  ant_code
               ,ant_height
               ,azimuth
               ,beamwidth_horizontal AS hbwd
               ,cover_area_type
               ,cover_hotspot_type
               ,cover_road_type
               ,dirction_type
               ,downtilt_mechanical  AS mechanicaldowntilt
               ,is_rru_integrated
               ,latitude             AS antlat
               ,longitude            AS antlon
               ,beamwidth_vertical   AS vbwd
               ,opposite_nat_name
               ,opposite_prv_name
               ,opposite_reg_name
        FROM itg_cm_lte_ant_d
        WHERE p_provincecode = 330000
        -- Generated By AI Start (Cursor)
        AND p_date = '2026-03-25'
        -- Generated By AI End (Cursor)
        AND ant_code > ''
        AND ant_code is not null
        AND ant_code <> 'null'
    ) ant
    ON ant.ant_code = cel.ant_code
    LEFT JOIN
    (
        SELECT  longitude AS rrulon
               ,latitude  AS rrulat
               ,cel_object_rdn
               ,serialid as rru_serialid
        FROM itg_cm_lte_rru_d
        WHERE p_provincecode = 330000
        -- Generated By AI Start (Cursor)
        AND p_date = '2026-03-25'
        -- Generated By AI End (Cursor)
        AND cel_object_rdn > ''
        AND cel_object_rdn is not null
        AND cel_object_rdn <> 'null'
    ) rru
    ON rru.cel_object_rdn = cel.cel_code
    LEFT JOIN
    (
        SELECT  room_code
               ,longitude AS roomlon
               ,latitude  AS roomlat
        FROM itg_cm_lte_room_d
        WHERE p_provincecode = 330000
        -- Generated By AI Start (Cursor)
        AND p_date = '2026-03-25'
        -- Generated By AI End (Cursor)
        AND room_code > ''
        AND room_code is not null
        AND room_code <> 'null'
    ) room
    ON room.room_code = cel.room_code
    WHERE enb_id is not null
    AND cel_id is not null
) ranked_cfg_sector_lte_refactor_temp
WHERE rank = 1;

-- 从上面的表查询异常小区经纬度的小区信息
SELECT
    *
FROM
cfg_sector_lte_refactor_temp
where oid in ('316026_24',
'316026_23',
'357176_10',
'357176_11') limit 10;

异常小区cellkey样例 :

357176_11       1.202564        3.084351
316026_23       1.217973        2.994435
357176_10       1.202564        3.084351
316026_24       1.217973        2.994435