import re

input_file = r'e:\CursorWorkspace\DTSW_AI\wldsj_ddl\hx_ddl_20260427_final.sql'

with open(input_file, 'r', encoding='utf-8') as f:
    content = f.read()

def repl(m):
    return f"-- Generated By AI Start (Cursor)\n{m.group(1)}LOCATION 'hdfs://pocdeploytest-3:8020/hive_external/wldsj_jt_zxvmax/{m.group(2)}'\n-- Generated By AI End (Cursor)"

# We don't want to replace ones that ALREADY have 'hdfs://pocdeploytest-3:8020/hive_external/wldsj_jt_zxvmax'
# Wait, the ones replaced previously already have 'hdfs...', we are only replacing 'viewfs://...'
new_content, count = re.subn(r'(^[ \t]*)LOCATION\s+\'viewfs://nsX(?:.*?)/(zxvmax(?:/.*?|))\'', repl, content, flags=re.MULTILINE)

# Let's also remove any strange GC logs like " Concurrent marking:\n-^^^"
new_content = re.sub(r'(?i)\n* Concurrent marking:.*?(?=\bCREATE|\Z)', '\n\n', new_content, flags=re.DOTALL)

with open(input_file, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Replaced {count} occurrences of remaining viewfs paths, and cleaned up garbage GC logs.")