spark-sql> desc aggr_nr_pm_cel_h;
day     string  日期
hour    int     小时
provincecode    int     省编码
province        string  省名称
citycode        int     城市编码
city    string  城市名称
districtcode    int     区县编码
district        string  区县名称
bandwidth_dl    double  下行带宽
data_source     int     数据来源。0：电信承建；1：联通承建
plmn    int     逻辑小区plmn
vendor  string  设备厂家。ZTE、HW、DT、NK、ER
dn      string  逻辑小区DU_DN值
master_phy_cell_id      string  承建方小区ID
related_gnb_dn  string  基站DN值
related_gnb_id  string  基站ID
related_gnb_userlabel   string  基站名称
cel_id  string  逻辑小区ID
celdu_id_local  string  逻辑小区内部ID
userlabel       string  逻辑小区名称
cellkey string  小区cellkey
drb_actmeannumdl        double  下行平均激活DRB数 
drb_actmaxnumdl bigint  下行最大激活DRB数 
rlc_rxbytesul   double  上行RLC层用户面流量 
rlc_txbytesdl   double  下行RLC层用户面流量 
rlc_lastrxbytesul       double  上行RLC层用户面尾包字节数
rlc_lasttxbytesdl       double  下行RLC层用户面尾包字节数
rlc_rxtimeul_exceptlastslot     double  上行RLC层用户面数据接收总时长（不含最后一个slot）
rlc_txtimedl_exceptlastslot     double  下行RLC层用户面数据发送总时长（不含最后一个slot）
nsa_rlc_rxbytesul       double  NSA小区空口上行业务流量 
nsa_rlc_txbytesdl       double  NSA小区空口下行业务流量 
rlc_sdutxpktdl  double  下行RLC层用户面包总数（SDU）
rlc_sdutxpktlossdl      double  下行RLC层用户面丢包数
rlc_pdutxpktul  double  上行RLC层用户面包总数（PDU）
rlc_pduretranspktul     double  上行RLC层用户面重传包数
rlc_pdurxpktdl  double  下行RLC层用户面包总数（PDU）
rlc_pduretranspktdl     double  下行RLC层用户面重传包数
vonr_rlc_sdutxpktdl     bigint  VoNR语音下行RLC层包总数（SDU）
vonr_rlc_sdulosstxpktdl bigint  VoNR语音下行RLC层丟包数
vonr_time_from_lceldu   bigint  VoNR语音总时长
vinr_time_from_lceldu   bigint  ViNR视频总时长
rrc_connmean    double  平均RRC连接用户数
rrc_connmax     bigint  最大RRC连接用户数
drb_nummean     double  平均DRB数
drb_nummax      bigint  最大DRB数
qos_nummean     double  平均QosFlow数
qos_nummax      bigint  最大QosFlow数
ca_usercapacitymean     double  平均CA能力用户数
ca_usercapacitymax      bigint  最大CA能力用户数
ng_connatt      bigint  NG信令连接建立尝试次数
ng_connsucc     bigint  NG信令连接建立成功次数
qos_estabreq    bigint  QosFlow建立请求数
qos_estabreq_5qi1       bigint  QosFlow建立请求数_5QI1
qos_estabreq_5qi2       bigint  QosFlow建立请求数_5QI2
qos_estabreq_5qi3       bigint  QosFlow建立请求数_5QI3
qos_estabreq_5qi4       bigint  QosFlow建立请求数_5QI4
qos_estabreq_5qi5       bigint  QosFlow建立请求数_5QI5
qos_estabreq_5qi6       bigint  QosFlow建立请求数_5QI6
qos_estabreq_5qi7       bigint  QosFlow建立请求数_5QI7
qos_estabreq_5qi8       bigint  QosFlow建立请求数_5QI8
qos_estabreq_5qi9       bigint  QosFlow建立请求数_5QI9
qos_estabsucc   bigint  QosFlow建立成功数
qos_estabsucc_5qi1      bigint  QosFlow建立成功数_5QI1
qos_estabsucc_5qi2      bigint  QosFlow建立成功数_5QI2
qos_estabsucc_5qi3      bigint  QosFlow建立成功数_5QI3
qos_estabsucc_5qi4      bigint  QosFlow建立成功数_5QI4
qos_estabsucc_5qi5      bigint  QosFlow建立成功数_5QI5
qos_estabsucc_5qi6      bigint  QosFlow建立成功数_5QI6
qos_estabsucc_5qi7      bigint  QosFlow建立成功数_5QI7
qos_estabsucc_5qi8      bigint  QosFlow建立成功数_5QI8
qos_estabsucc_5qi9      bigint  QosFlow建立成功数_5QI9
qos_modifyreq   bigint  QosFlow修改请求数
qos_modifysucc  bigint  QosFlow修改成功数
qos_estabfail_radioresources    bigint  QosFlow建立失败数（无线资源不足）
qos_estabfail_radiotimeout      bigint  QosFlow建立失败数（空口定时器超时）
qos_estabfail_others    bigint  QosFlow建立失败数（其它原因）
ue_contextrelease       bigint  UE上下文释放总数
ue_normalcontextrelease bigint  UE上下文正常释放数
qos_release     bigint  QosFlow释放总数
qos_normalrelease       bigint  QosFlow正常释放数
ho_attintragnb  bigint  站内切换请求次数
ho_succintragnb bigint  站内切换成功次数
ho_attbyxn      bigint  Xn接口切换请求次数
ho_succbyxn     bigint  Xn接口切换成功次数
ho_attbyng      bigint  Ng接口切换请求次数
ho_succbyng     bigint  Ng接口切换成功次数
ho_attsamefreq  bigint  同频切换请求次数
ho_succsamefreq bigint  同频切换成功次数
ho_attdifffreq  bigint  异频切换请求次数
ho_succdifffreq bigint  异频切换成功次数
ho_attfromgutrantoeutran        bigint  5G下切4G请求次数
ho_succfromgutrantoeutran       bigint  5G下切4G成功次数
rd_numfromgutrantoeutran        bigint  5G重定向到4G的总次数
ho_attfromeutrantogutran        bigint  基于覆盖4G切5G请求次数
ho_succfromeutrantogutran       bigint  基于覆盖4G切5G成功次数
pdcp_rxbytesul  double  上行PDCP层业务流量
pdcp_txbytesdl  double  下行PDCP层业务流量
nsa_pdcp_rxbytesul      double  上行PDCP层用户面流量
nsa_pdcp_txbytesdl      double  下行PDCP层用户面流量
vonr_usermean   double  VoNR语音平均用户数
vonr_usermax    bigint  VoNR语音峰值用户数
vinr_usermean   double  ViNR视频平均用户数
vinr_usermax    bigint  ViNR视频峰值用户数
qos_initialestabreq     bigint  初始QosFlow建立请求数
qos_initialestabreq_5qi1        bigint  初始QosFlow建立请求数_5QI1
qos_initialestabreq_5qi2        bigint  初始QosFlow建立请求数_5QI2
qos_initialestabreq_5qi3        bigint  初始QosFlow建立请求数_5QI3
qos_initialestabreq_5qi4        bigint  初始QosFlow建立请求数_5QI4
qos_initialestabreq_5qi5        bigint  初始QosFlow建立请求数_5QI5
qos_initialestabreq_5qi6        bigint  初始QosFlow建立请求数_5QI6
qos_initialestabreq_5qi7        bigint  初始QosFlow建立请求数_5QI7
qos_initialestabreq_5qi8        bigint  初始QosFlow建立请求数_5QI8
qos_initialestabreq_5qi9        bigint  初始QosFlow建立请求数_5QI9
qos_initialestabsucc    bigint  初始QosFlow建立成功数
qos_initialestabsucc_5qi1       bigint  初始QosFlow建立成功数_5QI1
qos_initialestabsucc_5qi2       bigint  初始QosFlow建立成功数_5QI2
qos_initialestabsucc_5qi3       bigint  初始QosFlow建立成功数_5QI3
qos_initialestabsucc_5qi4       bigint  初始QosFlow建立成功数_5QI4
qos_initialestabsucc_5qi5       bigint  初始QosFlow建立成功数_5QI5
qos_initialestabsucc_5qi6       bigint  初始QosFlow建立成功数_5QI6
qos_initialestabsucc_5qi7       bigint  初始QosFlow建立成功数_5QI7
qos_initialestabsucc_5qi8       bigint  初始QosFlow建立成功数_5QI8
qos_initialestabsucc_5qi9       bigint  初始QosFlow建立成功数_5QI9
ue_contextestabreq      bigint  UE上下文建立请求次数
ue_contextestabsucc     bigint  UE上下文建立成功次数
vonr_connreq    bigint  VoNR语音建立请求数
vonr_connsucc   bigint  VoNR语音建立成功数
vinr_connreq    bigint  ViNR视频建立请求数
vinr_connsucc   bigint  ViNR视频建立成功数
vonr_qos_estabfail_radioresources       bigint  VoNR语音QoSflow建立失败个数（无线资源不足）
vonr_qos_estabfail_radiotimeout bigint  VoNR语音QoSflow建立失败个数（空口定时器超时）
vonr_qos_estabfail_slicesupported       bigint  VoNR语音QoSflow建立失败个数（网络切片不支持）
vonr_qos_estabfail_sliceresources       bigint  VoNR语音QoSflow建立失败个数（切片资源受限）
ue_contextrelbyamf      bigint  AMF发起的UE上下文释放总数
ue_contextrelbygnb      bigint  gNodeB发起的UE上下文释放总数
ue_contextnormalrelbygnb        bigint  gNodeB发起的UE上下文正常释放数
qos_releasebyamf        bigint  AMF发起的QosFlow释放总数
qos_releasebygnb        bigint  gNodeB发起的QosFlow释放总数
qos_relnormalbygnb      bigint  gNodeB发起的QosFlow正常释放数
vonr_releasesum bigint  VoNR语音释放总数
vonr_normalrelease      bigint  VoNR语音正常释放数
vinr_releasesum bigint  ViNR视频释放总数
vinr_normalrelease      bigint  ViNR视频正常释放数
ims_releasesum  bigint  IMS信令释放总数
ims_normalrelease       bigint  IMS信令正常释放数
vonr_time_from_lcelcu   bigint  VoNR语音总时长
vinr_time_from_lcelcu   bigint  ViNR视频总时长
vonr_ho_attintragnb     bigint  VoNR语音站内切换请求次数
vonr_ho_succintragnb    bigint  VoNR语音站内切换成功次数
vonr_ho_attbyxn bigint  VoNR语音Xn接口切换请求次数
vonr_ho_succbyxn        bigint  VoNR语音Xn接口切换成功次数
vonr_ho_attbyng bigint  VoNR语音Ng接口切换请求次数
vonr_ho_succbyng        bigint  VoNR语音Ng接口切换成功次数
vonr_ho_attsamefreq     bigint  VoNR语音同频切换请求次数
vonr_ho_succsamefreq    bigint  VoNR语音同频切换成功次数
vonr_ho_attdifffreq     bigint  VoNR语音异频切换请求次数
vonr_ho_succdifffreq    bigint  VoNR语音异频切换成功次数
vonr_ho_atttovolte      bigint  VoNR语音向VoLTE切换请求次数
vonr_ho_succtovolte     bigint  VoNR语音向VoLTE切换成功次数
vonr_rxbytesul  double  VoNR语音上行业务流量
vonr_txbytesdl  double  VoNR语音下行业务流量
pdcp_rxpktul    bigint  上行PDCP层用户面包总数
pdcp_rxpktlossul        bigint  上行PDCP层用户面丢包数
pdcp_txpktdl    bigint  下行PDCP层用户面包总数
pdcp_txpktdiscarddl     bigint  下行PDCP层用户面弃包数
vonr_pdcp_rxpktul       bigint  VoNR语音上行PDCP层包总数
vonr_pdcp_losspktul     bigint  VoNR语音上行PDCP层丢包数
vonr_pdcp_rxpktdl       bigint  VoNR语音下行PDCP层包总数
vonr_pdcp_discardpktdl  bigint  VoNR语音下行PDCP层弃包数
vonr_rtp_rxpktul        bigint  VoNR语音上行RTP包总数
vonr_rtp_losspktul      bigint  VoNR语音上行RTP丢包数
vonr_rtp_rxpktdl        bigint  VoNR语音下行RTP包总数
vonr_rtp_losspktdl      bigint  VoNR语音下行RTP丢包数
ho_5gstoepsreqbydata    bigint  数据触发NR切换LTE请求次数
ho_5gstoepsreqbyvoice   bigint  语音触发NR切换LTE请求次数
ho_5gstoepssuccbydata   bigint  数据触发NR切换LTE成功次数
ho_5gstoepssuccbyvoice  bigint  语音触发NR切换LTE成功次数
intra_5gstoepsbydata    bigint  数据原因触发5G互操作到4G的总次数
intra_5gstoepsbyvoice   bigint  语音业务触发5G互操作到4G的总次数
rrc_connreq     bigint  RRC连接建立请求次数
rrc_connsucc    bigint  RRC连接建立成功次数
rrc_connestabfail_radiotimeout  bigint  RRC连接建立失败次数（空口定时器超时）
rrc_connestabfail_cell  bigint  RRC连接建立失败次数(小区拒绝)
rrc_connestabfail_others        bigint  RRC连接建立失败次数（其它原因）
rrc_connreestabreq      bigint  RRC连接重建请求次数
rrc_connreestabsucc     bigint  RRC连接重建成功次数
prb_usedul      bigint  小区上行PRB占用总数
prb_availul     bigint  小区上行PRB可用总数
prb_useddl      bigint  小区下行PRB占用总数
prb_availdl     bigint  小区下行PRB可用总数
prb_puschusedul bigint  上行PUSCH_PRB占用总数
prb_pdschuseddl bigint  下行PDSCH_PRB占用总数
cce_pdcchuseddl bigint  PDCCH信道CCE占用个数
cce_pdcchavaildl        bigint  PDCCH信道CCE可用个数
nsa_prb_usedul  bigint  NSA小区上行PRB占用总数
nsa_prb_availul bigint  NSA小区上行PRB可用总数
nsa_prb_useddl  bigint  NSA小区下行PRB占用总数
nsa_prb_availdl bigint  NSA小区下行PRB可用总数
nsa_prb_puschusedul     bigint  NSA小区上行PUSCH_PRB占用总数
nsa_prb_pdschuseddl     bigint  NSA小区下行PDSCH_PRB占用总数
nsa_cce_pdcchuseddl     bigint  NSA小区PDCCH信道CCE占用个数
nsa_cce_pdcchavaildl    bigint  PDCCH 信道CCE 可用个数 
phy_meannlperprbul      double  小区上行每PRB平均干扰电平
phy_maxnlperprbul       double  小区上行每PRB最大干扰电平
cqi_numintable  bigint  CQI_Table表UE上报的CQI次数
cqi_numintable_cqi0     bigint  CQI_Table表UE上报的CQI0次数
cqi_numintable_cqi1     bigint  CQI_Table表UE上报的CQI1次数
cqi_numintable_cqi2     bigint  CQI_Table表UE上报的CQI2次数
cqi_numintable_cqi3     bigint  CQI_Table表UE上报的CQI3次数
cqi_numintable_cqi4     bigint  CQI_Table表UE上报的CQI4次数
cqi_numintable_cqi5     bigint  CQI_Table表UE上报的CQI5次数
cqi_numintable_cqi6     bigint  CQI_Table表UE上报的CQI6次数
cqi_numintable_cqi7     bigint  CQI_Table表UE上报的CQI7次数
cqi_numintable_cqi8     bigint  CQI_Table表UE上报的CQI8次数
cqi_numintable_cqi9     bigint  CQI_Table表UE上报的CQI9次数
cqi_numintable_cqi10    bigint  CQI_Table表UE上报的CQI10次数
cqi_numintable_cqi11    bigint  CQI_Table表UE上报的CQI11次数
cqi_numintable_cqi12    bigint  CQI_Table表UE上报的CQI12次数
cqi_numintable_cqi13    bigint  CQI_Table表UE上报的CQI13次数
cqi_numintable_cqi14    bigint  CQI_Table表UE上报的CQI14次数
cqi_numintable_cqi15    bigint  CQI_Table表UE上报的CQI15次数
cqi_numintable2 bigint  CQI_Table2表UE上报的CQI次数
cqi_numintable2_cqi0    bigint  CQI_Table2表UE上报的CQI0次数
cqi_numintable2_cqi1    bigint  CQI_Table2表UE上报的CQI1次数
cqi_numintable2_cqi2    bigint  CQI_Table2表UE上报的CQI2次数
cqi_numintable2_cqi3    bigint  CQI_Table2表UE上报的CQI3次数
cqi_numintable2_cqi4    bigint  CQI_Table2表UE上报的CQI4次数
cqi_numintable2_cqi5    bigint  CQI_Table2表UE上报的CQI5次数
cqi_numintable2_cqi6    bigint  CQI_Table2表UE上报的CQI6次数
cqi_numintable2_cqi7    bigint  CQI_Table2表UE上报的CQI7次数
cqi_numintable2_cqi8    bigint  CQI_Table2表UE上报的CQI8次数
cqi_numintable2_cqi9    bigint  CQI_Table2表UE上报的CQI9次数
cqi_numintable2_cqi10   bigint  CQI_Table2表UE上报的CQI10次数
cqi_numintable2_cqi11   bigint  CQI_Table2表UE上报的CQI11次数
cqi_numintable2_cqi12   bigint  CQI_Table2表UE上报的CQI12次数
cqi_numintable2_cqi13   bigint  CQI_Table2表UE上报的CQI13次数
cqi_numintable2_cqi14   bigint  CQI_Table2表UE上报的CQI14次数
cqi_numintable2_cqi15   bigint  CQI_Table2表UE上报的CQI15次数
p_provincecode  int
p_date  string
p_hour  int



         > desc dm_base_cell_info_5g_d;
day     string  NULL
operation_state int     NULL
province_code   int     NULL
province_name   string  NULL
city_code       int     NULL
city_name       string  NULL
district_code   int     NULL
district_name   string  NULL
cell_name       string  NULL
gnbid_name      string  NULL
indoor_flag     int     NULL
open_state      int     NULL
cell_id int     NULL
gnbid   int     NULL
tac     bigint  NULL
pci     int     NULL
mod3    int     NULL
freq_brand      string  NULL
band_width_dl   string  NULL
duplex_mode     string  NULL
vendor  string  NULL
equipment_type  string  NULL
equipment_version       string  NULL
enodeb_type     string  NULL
antenna_lot     double  NULL
antenna_lat     double  NULL
antenna_height  double  NULL
azimuth double  NULL
downdip double  NULL
nr_framework    string  NULL
4g_enbid        string  NULL
last_modified   string  NULL
modify_id       string  NULL
cell_key        string  NULL
provincecode    int     NULL
scene_type      string  NULL
main_type       string  NULL
station_distance        double  NULL
is_share_station        int     NULL
share_station_distance  double  NULL
nr_arfcn        int     NULL
contractor      string  NULL
p_provincecode  int     NULL
p_date  string  NULL
# Partition Information
# col_name      data_type       comment
p_provincecode  int     NULL
p_date  string  NULL