CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_video_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `video_play_success` INT COMMENT '',
  `video_play_wait_time` BIGINT COMMENT '',
  `video_play_halt_count` BIGINT COMMENT '',
  `video_recover_time` BIGINT COMMENT '',
  `first_data_pkg_time` BIGINT COMMENT '',
  `last_data_pkg_time` BIGINT COMMENT '',
  `connection_count` BIGINT COMMENT '',
  `video_size` BIGINT COMMENT '',
  `video_throughput` BIGINT COMMENT '',
  `video_type` INT COMMENT '',
  `video_bit_rate` BIGINT COMMENT '',
  `video_cache_throughput` BIGINT COMMENT '',
  `destination_url` STRING COMMENT '',
  `host` STRING COMMENT '',
  `cached_video_size` BIGINT COMMENT '',
  `cached_video_duration` BIGINT COMMENT '',
  `video_resolution_level` BIGINT COMMENT '',
  `video_fluency_level` BIGINT COMMENT '',
  `video_resolution` STRING COMMENT '')
COMMENT 'ods_5gdpi_video_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_video_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468503')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_vonr_gm_telecom_q`(
  `interface` INT,
  `xdr_id` STRING,
  `supi` STRING,
  `pei` STRING,
  `msisdn` STRING,
  `rat` INT,
  `home_province` STRING,
  `procedure_type` INT,
  `procedure_start_time` BIGINT,
  `procedure_end_time` BIGINT,
  `service_type` INT,
  `procedure_status` INT,
  `calling_number` STRING,
  `called_number` STRING,
  `smsc_addr` STRING,
  `calling_party_uri` STRING,
  `request_uri` STRING,
  `user_ip` STRING,
  `callid` STRING,
  `icid` STRING,
  `source_ne_ip` STRING,
  `source_ne_port` INT,
  `dest_ne_ip` STRING,
  `dest_ne_port` INT,
  `call_side` INT,
  `source_access_type` INT,
  `source_eci` BIGINT,
  `source_tac` INT,
  `source_imsi` STRING,
  `source_imei` STRING,
  `source_sbc_domain` STRING,
  `dest_access_type` INT,
  `dest_eci` BIGINT,
  `dest_tac` INT,
  `dest_imsi` STRING,
  `dest_imei` STRING,
  `dest_sbc_domain` STRING,
  `auth_type` INT,
  `expires_time_req` BIGINT,
  `expires_time_rsp` BIGINT,
  `calling_sdp_ip_addr` STRING,
  `calling_audio_sdp_port` INT,
  `calling_video_sdp_port` INT,
  `called_sdp_ip_addr` STRING,
  `called_audio_sdp_port` INT,
  `called_video_port` INT,
  `audio_codec` INT,
  `video_codec` INT,
  `redirecting_party_address` STRING,
  `original_party_address` STRING,
  `privacy` STRING,
  `redirect_reason` INT,
  `response_code` INT,
  `finish_warning_code` INT,
  `finish_reason_protocol` INT,
  `finish_reason_cause` INT,
  `183_reason_protocol` INT,
  `183_reason_cause` INT,
  `call_fail_end` INT,
  `first_fail_time` BIGINT,
  `first_fail_ne_ip` STRING,
  `first_fail_transaction` INT,
  `progress_time` BIGINT,
  `prack_time` BIGINT,
  `update_time_1` BIGINT,
  `update_time_2` BIGINT,
  `update_time_3` BIGINT,
  `alerting_time` BIGINT,
  `answer_time` BIGINT,
  `release_time` BIGINT,
  `call_duration` BIGINT,
  `auth_req_time` BIGINT,
  `auth_rsp_time` BIGINT)
PARTITIONED BY (`p_provincecode` INT, `p_date` STRING, `p_hour` INT, `p_quarter` INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_vonr_gm_telecom_q'
TBLPROPERTIES (
  'transient_lastDdlTime' = '1758784511',
  'field.delim' = '|',
  'serialization.format' = '|')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_vonr_session_telecom_q`(
  `interface` INT,
  `xdr_id` STRING,
  `supi` STRING,
  `pei` STRING,
  `msisdn` STRING,
  `rat` INT,
  `home_province` STRING,
  `session_id` BIGINT,
  `service_type` INT,
  `ul_slice_num` INT,
  `dl_slice_num` INT,
  `session_start_time` BIGINT,
  `session_end_time` BIGINT,
  `source_ne_ip` STRING,
  `source_ne_port` INT,
  `dest_ne_ip` STRING,
  `dest_ne_port` INT,
  `user_type` INT,
  `dest_imsi` STRING,
  `dest_imei` STRING,
  `dest_msisdn` STRING,
  `source_ip` STRING,
  `source_port` INT,
  `dest_ip` STRING,
  `dest_port` INT,
  `source_start_eci` BIGINT,
  `source_end_eci` BIGINT,
  `dest_start_eci` BIGINT,
  `dest_end_eci` BIGINT,
  `service_rat_type` INT,
  `codec_type` INT,
  `uplink_codec_rate` DOUBLE,
  `downlink_codec_rate` DOUBLE,
  `ul_frame_rate` DOUBLE,
  `dl_frame_rate` DOUBLE,
  `ul_resolution_width` INT,
  `ul_resolution_height` INT,
  `dl_resolution_width` INT,
  `dl_resolution_height` INT,
  `ul_rtp_packet_expected` BIGINT,
  `ul_rtp_packet_actual` BIGINT,
  `ul_rtp_packet_loss` BIGINT,
  `ul_rtp_jitter_avg` BIGINT,
  `ul_rtp_max_consecutive_packet_loss` INT,
  `ul_rtcp_packet_expected` BIGINT,
  `ul_rtcp_packet_loss` BIGINT,
  `ul_rtcp_jitter_avg` BIGINT,
  `dl_rtp_packet_expected` BIGINT,
  `dl_rtp_packet_actual` BIGINT,
  `dl_rtp_packet_loss` BIGINT,
  `dl_rtp_jitter_avg` BIGINT,
  `dl_rtp_max_consecutive_packet_loss` INT,
  `dl_rtcp_packet_expected` BIGINT,
  `dl_rtcp_packet_loss` BIGINT,
  `dl_rtcp_jitter_avg` BIGINT,
  `rtcp_ring_delay` BIGINT,
  `session_end_status` INT,
  `ul_ssrc` BIGINT,
  `dl_ssrc` BIGINT,
  `ul_ssrc_rtcp` BIGINT,
  `dl_ssrc_rtcp` BIGINT,
  `ul_disorder_num` BIGINT,
  `dl_disorder_num` BIGINT,
  `avg_rtp_delay` BIGINT)
PARTITIONED BY (`p_provincecode` INT, `p_date` STRING, `p_hour` INT, `p_quarter` INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_vonr_session_telecom_q'
TBLPROPERTIES (
  'transient_lastDdlTime' = '1758784239',
  'field.delim' = '|',
  'serialization.format' = '|')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_vonr_slice_telecom_q`(
  `interface` INT,
  `xdr_id` STRING,
  `supi` STRING,
  `pei` STRING,
  `msisdn` STRING,
  `rat` INT,
  `home_province` STRING,
  `session_id` BIGINT,
  `service_type` INT,
  `direction` INT,
  `slice_id` INT,
  `slice_start_time` BIGINT,
  `slice_end_time` BIGINT,
  `source_start_eci` BIGINT,
  `source_end_eci` BIGINT,
  `dest_start_eci` BIGINT,
  `dest_end_eci` BIGINT,
  `source_ho_mark` INT,
  `dest_ho_mark` INT,
  `codec_type` INT,
  `codec_rate` DOUBLE,
  `frame_rate` DOUBLE,
  `resolution_width` INT,
  `resolution_height` INT,
  `rtp_packet_expected` BIGINT,
  `rtp_packet_actual` BIGINT,
  `rtp_packet_loss` BIGINT,
  `rtp_nonsid_packet_loss` BIGINT,
  `rtp_jitter_avg` BIGINT,
  `rtp_jitter_max` BIGINT,
  `rtp_max_consecutive_packet_loss` INT,
  `rtp_max_consecutive_nonsid_packet_loss` INT,
  `rtp_max_delay` INT,
  `rtcp_packet_expected` BIGINT,
  `rtcp_fraction_lost` INT,
  `rtcppacket_loss` BIGINT,
  `rtcp_jitter` BIGINT,
  `rtcp_ring_delay` BIGINT,
  `session_end_mark` INT,
  `disordernum` BIGINT,
  `ssrc` BIGINT,
  `ssrc_rtcp` BIGINT,
  `callok` INT,
  `handoverstageflag` INT,
  `dlswallowflag` INT,
  `ulswallowflag` INT,
  `number_for_specific_rtp_consecutive_packet_loss_1` INT,
  `number_for_specific_rtp_consecutive_packet_loss_2` INT,
  `number_for_specific_rtp_consecutive_packet_loss_3` INT,
  `lastseqnum` BIGINT,
  `lasttimestamp` BIGINT,
  `rtp_nonsid_packet_actual` INT,
  `rtp_relative_delay_avg` INT,
  `rtp_relative_delay_max` INT,
  `rtp_relative_delay_exceeded_time` INT,
  `rtp_jitter_exceeded_time` INT)
PARTITIONED BY (`p_provincecode` INT, `p_date` STRING, `p_hour` INT, `p_quarter` INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_vonr_slice_telecom_q'
TBLPROPERTIES (
  'transient_lastDdlTime' = '1758784242',
  'field.delim' = '|',
  'serialization.format' = '|')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n10_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `udm_ip_addr` STRING COMMENT '',
  `smf_ip_addr` STRING COMMENT '',
  `udm_port` INT COMMENT '',
  `smf_port` INT COMMENT '',
  `sub_procedure_type` INT COMMENT '',
  `pdusession_id` INT COMMENT '',
  `snssai_sst` INT COMMENT '',
  `snssai_sd` STRING COMMENT '',
  `dnn` STRING COMMENT '',
  `defaultsessiontype` INT COMMENT '',
  `sessiontype` INT COMMENT '',
  `defaultsscmode` INT COMMENT '',
  `sscmode` INT COMMENT '',
  `5qi` INT COMMENT '',
  `location_type` INT COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` BIGINT COMMENT '')
COMMENT 'ods_5gdpi_n10_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n10_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758781792')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n11_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `amf_address` STRING COMMENT '',
  `smf_address` STRING COMMENT '',
  `amf_port` INT COMMENT '',
  `smf_port` INT COMMENT '',
  `request_cause` INT COMMENT '',
  `sub_procedure_type` INT COMMENT '',
  `pdu_session_id` INT COMMENT '',
  `snssai_sst` INT COMMENT '',
  `snssai_sd` STRING COMMENT '',
  `dnn` STRING COMMENT '',
  `requesttype` INT COMMENT '',
  `pdu_session_type` INT COMMENT '',
  `n3_upf_addr` STRING COMMENT '',
  `n3_upf_teid` INT COMMENT '',
  `n3_an_addr` STRING COMMENT '',
  `n3_an_teid` INT COMMENT '',
  `n1n2msg_tsf_cause` INT COMMENT '',
  `ngapietype` INT COMMENT '',
  `user_ipv4` STRING COMMENT '',
  `user_ipv6` STRING COMMENT '',
  `hostate` INT COMMENT '',
  `access_type` INT COMMENT '',
  `location_type` INT COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` BIGINT COMMENT '')
COMMENT 'ods_5gdpi_n11_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n11_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758781934')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n12_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` INT COMMENT '',
  `procedure_end_time` INT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `amf_ip_addr` STRING COMMENT '',
  `ausf_ip_addr` STRING COMMENT '',
  `amf_port` INT COMMENT '',
  `ausf_port` INT COMMENT '',
  `auth_type` INT COMMENT '',
  `auth_result` INT COMMENT '',
  `suci` STRING COMMENT '')
COMMENT 'ods_5gdpi_n12_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n12_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758781946')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n14_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` INT COMMENT '',
  `procedure_end_time` INT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `source_amf_address` STRING COMMENT '',
  `destination_amf_address` STRING COMMENT '',
  `source_amf_port` INT COMMENT '',
  `destination_amf_port` INT COMMENT '',
  `sub_procedure_type` INT COMMENT '',
  `request_cause` INT COMMENT '',
  `user_ipv4` STRING COMMENT '',
  `user_ipv6` STRING COMMENT '',
  `transferreason` INT COMMENT '',
  `pdu_session_id` INT COMMENT '',
  `dnn` STRING COMMENT '',
  `access_type` INT COMMENT '',
  `location_type` INT COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` BIGINT COMMENT '')
COMMENT 'ods_5gdpi_n14_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n14_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758782063')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n26_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `mme_address` STRING COMMENT '',
  `amf_address` STRING COMMENT '',
  `mme_port` INT COMMENT '',
  `amf_port` INT COMMENT '',
  `mme_control_teid` INT COMMENT '',
  `amf_control_teid` INT COMMENT '',
  `user_ipv4` STRING COMMENT '',
  `user_ipv6` STRING COMMENT '',
  `apn` STRING COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` BIGINT COMMENT '',
  `eps_bearer_number` INT COMMENT '',
  `bearer_id` INT COMMENT '',
  `bearer_type` INT COMMENT '',
  `bearer_qci` INT COMMENT '',
  `bearer_status` INT COMMENT '',
  `bearer_enb_mme_gtp_teid` INT COMMENT '',
  `bearer_sgw_gtp_teid` INT COMMENT '',
  `bearer_id_2` INT COMMENT '',
  `bearer_type_2` INT COMMENT '',
  `bearer_qci_2` INT COMMENT '',
  `bearer_status_2` INT COMMENT '',
  `bearer_enb_mme_gtp_teid_2` INT COMMENT '',
  `bearer_sgw_gtp_teid_2` INT COMMENT '',
  `bearer_id_3` INT COMMENT '',
  `bearer_type_3` INT COMMENT '',
  `bearer_qci_3` INT COMMENT '',
  `bearer_status_3` INT COMMENT '',
  `bearer_enb_mme_gtp_teid_3` INT COMMENT '',
  `bearer_sgw_gtp_teid_3` INT COMMENT '',
  `bearer_id_4` INT COMMENT '',
  `bearer_type_4` INT COMMENT '',
  `bearer_qci_4` INT COMMENT '',
  `bearer_status_4` INT COMMENT '',
  `bearer_enb_mme_gtp_teid_4` INT COMMENT '',
  `bearer_sgw_gtp_teid_4` INT COMMENT '',
  `bearer_id_5` INT COMMENT '',
  `bearer_type_5` INT COMMENT '',
  `bearer_qci_5` INT COMMENT '',
  `bearer_status_5` INT COMMENT '',
  `bearer_enb_mme_gtp_teid_5` INT COMMENT '',
  `bearer_sgw_gtp_teid_5` INT COMMENT '')
COMMENT 'ods_5gdpi_n26_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n26_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468610')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_coap_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `version` INT COMMENT '',
  `proceduretype` INT COMMENT '',
  `token` STRING COMMENT '',
  `requst_action` INT COMMENT '',
  `response_result` STRING COMMENT '',
  `status` INT COMMENT '',
  `firstrequesttime` INT COMMENT '',
  `acktime` INT COMMENT '',
  `lastrequesttime` INT COMMENT '',
  `retrans_ul_count` INT COMMENT '',
  `retrans_dl_count` INT COMMENT '',
  `direction` INT COMMENT '',
  `uri_port` INT COMMENT '',
  `destination_uri` STRING COMMENT '',
  `host` STRING COMMENT '',
  `proxy_uri` STRING COMMENT '',
  `proxy_scheme` STRING COMMENT '')
COMMENT 'ods_5gdpi_coap_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_coap_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468598')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_email_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `serverdomain` STRING COMMENT '',
  `username` STRING COMMENT '',
  `mailfrom` STRING COMMENT '',
  `mailto` STRING COMMENT '',
  `status` INT COMMENT '')
COMMENT 'ods_5gdpi_email_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_email_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468600')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_ftp_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `ueportfrom` INT COMMENT '',
  `ueportend` INT COMMENT '',
  `spportfrom` INT COMMENT '',
  `spportend` INT COMMENT '',
  `filename` STRING COMMENT '',
  `filesize` INT COMMENT '',
  `transflag` INT COMMENT '',
  `ftpstatus` INT COMMENT '',
  `delay` INT COMMENT '')
COMMENT 'ods_5gdpi_ftp_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_ftp_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468603')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_game_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `syntime` BIGINT COMMENT '',
  `synacktime` BIGINT COMMENT '',
  `acktime` BIGINT COMMENT '',
  `avg_delay` BIGINT COMMENT '')
COMMENT 'ods_5gdpi_game_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_game_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468605')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_mqtt_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `supi` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `dnn_apn` STRING COMMENT '',
  `destinationip` STRING COMMENT '',
  `destinationport` INT COMMENT '',
  `sourceip` STRING COMMENT '',
  `sourceport` INT COMMENT '',
  `upfip` STRING COMMENT '',
  `ncgi_ecgi` STRING COMMENT '',
  `tai` STRING COMMENT '',
  `visitedplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `protocolid` INT COMMENT '',
  `servicetype` STRING COMMENT '',
  `starttime` STRING COMMENT '',
  `endtime` STRING COMMENT '',
  `duration` BIGINT COMMENT '',
  `inputoctets` BIGINT COMMENT '',
  `outputoctets` BIGINT COMMENT '',
  `inputpacket` BIGINT COMMENT '',
  `outputpacket` BIGINT COMMENT '',
  `pduconnectionid` STRING COMMENT '',
  `recordclosecause` INT COMMENT '',
  `gnbip` STRING COMMENT '',
  `gnbgtp_teid` BIGINT COMMENT '',
  `upfgtp_teid` BIGINT COMMENT '',
  `home_province` STRING COMMENT '',
  `l4protocol` INT COMMENT '',
  `ultcpreorderingpacket` BIGINT COMMENT '',
  `dltcpreorderingpacket` BIGINT COMMENT '',
  `ultcp_retranspacket` BIGINT COMMENT '',
  `dltcp_retranspacket` BIGINT COMMENT '',
  `tcpsetupresponsedelay` BIGINT COMMENT '',
  `tcpsetupackdelay` BIGINT COMMENT '',
  `ulipfragpacks` BIGINT COMMENT '',
  `dlipfragpacks` BIGINT COMMENT '',
  `delay_setup_firsttransaction` BIGINT COMMENT '',
  `delay_firsttransaction_firstrespackt` BIGINT COMMENT '',
  `msssize` BIGINT COMMENT '',
  `tcpsynnumber` INT COMMENT '',
  `tcpconnectstate` INT COMMENT '',
  `sessionstopflag` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` BIGINT COMMENT '',
  `ul_session_ambr` BIGINT COMMENT '',
  `dl_session_ambr` BIGINT COMMENT '',
  `5qi` INT COMMENT '',
  `userfirsttcpwindow` BIGINT COMMENT '',
  `serverfirsttcpwindow` BIGINT COMMENT '',
  `userlasttcpwindow` BIGINT COMMENT '',
  `serverlasttcpwindow` BIGINT COMMENT '',
  `usermintcpwindow` BIGINT COMMENT '',
  `servermintcpwindow` BIGINT COMMENT '',
  `usermaxtcpwindow` BIGINT COMMENT '',
  `servermaxtcpwindow` BIGINT COMMENT '',
  `ul_data_transduration` BIGINT COMMENT '',
  `dl_datatransduration` BIGINT COMMENT '',
  `ul_packet_number_stg1` BIGINT COMMENT '',
  `ul_packet_number_stg2` BIGINT COMMENT '',
  `ul_packet_number_stg3` BIGINT COMMENT '',
  `ul_packet_number_stg4` BIGINT COMMENT '',
  `dl_packet_number_stg1` BIGINT COMMENT '',
  `dl_packet_number_stg2` BIGINT COMMENT '',
  `dl_packet_number_stg3` BIGINT COMMENT '',
  `dl_packet_number_stg4` BIGINT COMMENT '',
  `ul_average_packet_size` BIGINT COMMENT '',
  `dl_average_packet_size` BIGINT COMMENT '',
  `ul_average_interval` BIGINT COMMENT '',
  `dl_average_interval` BIGINT COMMENT '',
  `ul_average_jitter` BIGINT COMMENT '',
  `dl_average_jitter` BIGINT COMMENT '',
  `message_type` INT COMMENT '',
  `connect_return_code` INT COMMENT '',
  `qos` INT COMMENT '',
  `retain` INT COMMENT '',
  `username_flag` INT COMMENT '',
  `password_flag` INT COMMENT '',
  `will_flag` INT COMMENT '',
  `will_qos` INT COMMENT '',
  `will_retain` INT COMMENT '',
  `clean_session` INT COMMENT '',
  `keepalive` INT COMMENT '',
  `client_id` STRING COMMENT '',
  `will_topic` STRING COMMENT '',
  `will_message` STRING COMMENT '',
  `topic_name` STRING COMMENT '',
  `respdelay` INT COMMENT '',
  `syntime` INT COMMENT '',
  `synacktime` INT COMMENT '',
  `acktime` INT COMMENT '')
COMMENT 'ods_5gdpi_mqtt_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_mqtt_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468608')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n4_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `smf_ip_add` STRING COMMENT '',
  `upf_ip_add` STRING COMMENT '',
  `smf_port` INT COMMENT '',
  `upf_port` INT COMMENT '',
  `pdu_session_1_pdn_type` INT COMMENT '',
  `pdu_session_1_smf_f_seid` INT COMMENT '',
  `pdu_session_1_upf_f_seid` INT COMMENT '',
  `pdu_session_1_n3_upf_addr` STRING COMMENT '',
  `pdu_session_1_n3_upf_teid` INT COMMENT '',
  `pdu_session_1_n3_an_addr` STRING COMMENT '',
  `pdu_session_1_n3_an_teid` INT COMMENT '',
  `user_ipv4` STRING COMMENT '',
  `user_ipv6` STRING COMMENT '')
COMMENT 'ods_5gdpi_n4_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n4_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758769279')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n40_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `smf_ip_addr` STRING COMMENT '',
  `chf_ip_addr` STRING COMMENT '',
  `smf_port` INT COMMENT '',
  `chf_port` INT COMMENT '',
  `sub_procedure_type` INT COMMENT '',
  `nodefunctionality` INT COMMENT '',
  `nf_name` STRING COMMENT '',
  `nf_fqdn` STRING COMMENT '',
  `nf_plnmid` STRING COMMENT '',
  `invocationsequencenumber` INT COMMENT '',
  `onetimeevent` INT COMMENT '',
  `notifyuri` STRING COMMENT '',
  `failurehandling` INT COMMENT '',
  `sessionfailover` INT COMMENT '',
  `notificationtype` INT COMMENT '',
  `chargingid` INT COMMENT '',
  `unauthenticatedflag` INT COMMENT '',
  `roamerinout` INT COMMENT '',
  `location_type` INT COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` INT COMMENT '',
  `userlocationtime` STRING COMMENT '',
  `uetimezone` STRING COMMENT '',
  `unitcountinactivitytimer` INT COMMENT '',
  `nssai_sst` INT COMMENT '',
  `nssai_sd` INT COMMENT '',
  `pdusessionid` INT COMMENT '',
  `pdutype` INT COMMENT '',
  `sscmode` INT COMMENT '',
  `home_plmnid` STRING COMMENT '',
  `servingnodefunctionality` INT COMMENT '',
  `servingnf_name` STRING COMMENT '',
  `servingnf_ip_address` STRING COMMENT '',
  `servingnf_fqdn` STRING COMMENT '',
  `servingnf_plnmid` STRING COMMENT '',
  `amf_id` STRING COMMENT '',
  `servingcnplmnid` STRING COMMENT '',
  `rattype` INT COMMENT '',
  `dnnid` STRING COMMENT '',
  `chargingcharacteristics` STRING COMMENT '',
  `chargingcharacteristicsselectionmode` INT COMMENT '',
  `pdu_session_starttime` STRING COMMENT '',
  `pdu_session_stoptime` STRING COMMENT '',
  `3gpppsdataoffstatus` INT COMMENT '',
  `sessionstopindicator` INT COMMENT '',
  `pduipv4address` STRING COMMENT '',
  `pduipv6addresswithprefix` STRING COMMENT '',
  `diagnostics` INT COMMENT '',
  `auth_default_5qi` INT COMMENT '',
  `auth_default_arp` INT COMMENT '',
  `auth_default_prioritylevel` INT COMMENT '',
  `auth_default_averwindow` INT COMMENT '',
  `auth_default_maxdataburstvol` INT COMMENT '',
  `subscribeddefault_5qi` INT COMMENT '',
  `subscribeddefault_arp` INT COMMENT '',
  `subscribeddefault_prioritylevel` INT COMMENT '',
  `authorizedsession_uplink_ambr` INT COMMENT '',
  `authorizedsession_downlink_ambr` INT COMMENT '',
  `subscribedsession_uplink_ambr` INT COMMENT '',
  `subscribedsession_downlink_ambr` INT COMMENT '',
  `ransecondaryrattype` INT COMMENT '',
  `qosflowsusage_reports_number` INT COMMENT '',
  `fur_qfi` INT COMMENT '',
  `fur_starttimestamp` STRING COMMENT '',
  `fur_endtimestamp` STRING COMMENT '',
  `fur_downlinkvolume` INT COMMENT '',
  `fur_uplinkvolume` INT COMMENT '',
  `multipleunitusage_number` INT COMMENT '',
  `ratinggroup1` INT COMMENT '',
  `requestedunit_time1` INT COMMENT '',
  `requestedunit_totalvolume1` INT COMMENT '',
  `requestedunit_uplinkvolume1` INT COMMENT '',
  `requestedunit_downlinkvolume1` INT COMMENT '',
  `requestedunit_servicespecificunits1` INT COMMENT '',
  `usedunitcontainer_number1` INT COMMENT '',
  `usu1_serviceid1` INT COMMENT '',
  `usu1_quotamanagementindicator1` INT COMMENT '',
  `usu1_triggertimestamp1` STRING COMMENT '',
  `usu1_time1` INT COMMENT '',
  `usu1_totalvolume1` INT COMMENT '',
  `usu1_uplinkvolume1` INT COMMENT '',
  `usu1_downlinkvolume1` INT COMMENT '',
  `usu1_servicespecific_units1` INT COMMENT '',
  `usu1_eventtimestamps1` STRING COMMENT '',
  `usu1_timeoffirstusage1` STRING COMMENT '',
  `usu1_timeoflastusage1` STRING COMMENT '',
  `usu1_afcorrelationinformation` STRING COMMENT '',
  `usu1_uetimezone1` STRING COMMENT '',
  `usu1_rattype1` INT COMMENT '',
  `usu1_3gpppsdataoffstatus1` INT COMMENT '',
  `usu1_sponsoridentity1` STRING COMMENT '',
  `usu1_applicationserviceprovideridentity1` STRING COMMENT '',
  `usu1_chargingrulebasename1` STRING COMMENT '',
  `usu1_qosid1` STRING COMMENT '',
  `usu1_5qi1` INT COMMENT '',
  `usu1_maxbrul1` INT COMMENT '',
  `usu1_maxbrdl1` INT COMMENT '',
  `usu1_gbrul1` INT COMMENT '',
  `usu1_gbrdl1` INT COMMENT '',
  `usu1_arp1` INT COMMENT '',
  `usu1_qnc1` INT COMMENT '',
  `usu1_reflectiveqos1` INT COMMENT '',
  `usu1_sharingkeydl1` STRING COMMENT '',
  `usu1_sharingkeyul1` STRING COMMENT '',
  `usu1_prioritylevel1` INT COMMENT '',
  `usu1_averwindow1` INT COMMENT '',
  `usu1_maxdataburstvol1` INT COMMENT '',
  `usu1_maxpacketlossratedl1` INT COMMENT '',
  `usu1_maxpacketlossrateul1` INT COMMENT '',
  `usu1_defqosflowindication1` INT COMMENT '',
  `usu1_servingnodeid_number1` INT COMMENT '',
  `usu1_servingnodefunctionality1` INT COMMENT '',
  `usu1_servingnf_name1` STRING COMMENT '',
  `usu1_servingnf_ip_address1` STRING COMMENT '',
  `usu1_servingnf_fqdn1` STRING COMMENT '',
  `usu1_servingnf_plnmid1` STRING COMMENT '',
  `usu1_amf_id1` STRING COMMENT '',
  `usu1_usedunitcontainer_number` INT COMMENT '',
  `usu1_serviceid_1` INT COMMENT '',
  `usu1_quotamanagementindicator_1` INT COMMENT '',
  `usu1_triggertimestamp_1` STRING COMMENT '',
  `usu1_time_1` INT COMMENT '',
  `usu1_totalvolume_1` INT COMMENT '',
  `usu1_uplinkvolume_1` INT COMMENT '',
  `usu1_downlinkvolume_1` INT COMMENT '',
  `usu1_servicespecific_units_1` INT COMMENT '',
  `usu1_eventtimestamps_1` STRING COMMENT '',
  `usu1_localsequencenumber1` INT COMMENT '',
  `multipleunitinformation_number` INT COMMENT '',
  `mui_resultcode` INT COMMENT '',
  `mui_ratinggroup` INT COMMENT '',
  `mui_validitytime` INT COMMENT '',
  `mui_quotaholdingtime` INT COMMENT '',
  `mui_timequotathreshold` INT COMMENT '',
  `mui_volumequotathreshold` INT COMMENT '',
  `mui_unitquotathreshold` INT COMMENT '',
  `gu_tarifftimechange` STRING COMMENT '',
  `gu_time` INT COMMENT '',
  `gu_totalvolume` INT COMMENT '',
  `gu_uplinkvolume` INT COMMENT '',
  `gu_downlinkvolume` INT COMMENT '',
  `gu_servicespecificunits` INT COMMENT '',
  `fu_finalunitaction` INT COMMENT '',
  `fu_restrictionfilterrule` STRING COMMENT '',
  `fu_filterid` STRING COMMENT '',
  `fu_redirectaddresstype` INT COMMENT '',
  `fu_redirectserveraddress` STRING COMMENT '',
  `ra_serviceid` INT COMMENT '',
  `ra_ratinggroup` INT COMMENT '',
  `ra_quotamanagementindicator` INT COMMENT '')
COMMENT 'ods_5gdpi_n40_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n40_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1748468621')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n7_e2e_telecom_q`(
  `interface` INT COMMENT '',
  `xdr_id` STRING COMMENT '',
  `supi` STRING COMMENT '',
  `pei` STRING COMMENT '',
  `msisdn` STRING COMMENT '',
  `rat` INT COMMENT '',
  `home_province` STRING COMMENT '',
  `procedure_type` INT COMMENT '',
  `procedure_start_time` BIGINT COMMENT '',
  `procedure_end_time` BIGINT COMMENT '',
  `procedure_status` INT COMMENT '',
  `http_req_type` INT COMMENT '',
  `status_code` INT COMMENT '',
  `failure_cause` INT COMMENT '',
  `smf_ip_addr` STRING COMMENT '',
  `pcf_ip_addr` STRING COMMENT '',
  `smf_port` INT COMMENT '',
  `pcf_port` INT COMMENT '',
  `sub_procedure_type` INT COMMENT '',
  `pdusessionid` INT COMMENT '',
  `snssai_sst` INT COMMENT '',
  `snssai_sd` STRING COMMENT '',
  `dnn` STRING COMMENT '',
  `pdu_session_type` INT COMMENT '',
  `5qi` INT COMMENT '',
  `charging_mode` INT COMMENT '',
  `charging_id` INT COMMENT '',
  `ue_ipv4_addr` STRING COMMENT '',
  `ue_ipv6_prefix` STRING COMMENT '',
  `primary_chf_addr` STRING COMMENT '',
  `access_type` INT COMMENT '',
  `location_time` INT COMMENT '',
  `time_offset` INT COMMENT '',
  `daylight_saving_time` INT COMMENT '',
  `location_type` INT COMMENT '',
  `tac` INT COMMENT '',
  `cell_id` BIGINT COMMENT '')
COMMENT 'ods_5gdpi_n7_e2e_telecom_q'
PARTITIONED BY (`p_provincecode` INT COMMENT '', `p_date` STRING COMMENT '', `p_hour` INT COMMENT '', `p_quarter` INT COMMENT '')
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '|',
  'field.delim' = '|')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n7_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758782187')

createtab_stmt
CREATE EXTERNAL TABLE `hsdlake`.`ods_5gdpi_n8_e2e_telecom_q`(
  `interface` INT,
  `xdr_id` STRING,
  `supi` STRING,
  `pei` STRING,
  `msisdn` STRING,
  `rat` INT,
  `home_province` STRING,
  `procedure_type` INT,
  `procedure_start_time` BIGINT,
  `procedure_end_time` BIGINT,
  `procedure_status` INT,
  `http_req_type` INT,
  `status_code` INT,
  `failure_cause` INT,
  `amf_ip_addr` STRING,
  `udm_ip_addr` STRING,
  `amf_port` INT,
  `udm_port` INT,
  `sub_procedure_type` INT,
  `amf_region_id` INT,
  `amf_set_id` INT,
  `amf_pointer` INT,
  `imsvops` INT,
  `subsregtimer` INT,
  `ueusagetype` INT,
  `ratrestriction` INT,
  `restrictiontype` INT,
  `areainformation` BIGINT,
  `maxnumoftas` INT,
  `purge_flag` INT,
  `deregistration_reason` INT,
  `location_type` INT,
  `tac` INT,
  `cell_id` BIGINT)
PARTITIONED BY (`p_provincecode` INT, `p_date` STRING, `p_hour` INT, `p_quarter` INT)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1')
STORED AS
  INPUTFORMAT 'org.apache.hadoop.mapred.TextInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION 'hdfs://ns1/zxvmax/telecom/5g/ods/ods_5gdpi_n8_e2e_telecom_q'
TBLPROPERTIES (
  'bucketing_version' = '2',
  'transient_lastDdlTime' = '1758782301',
  'field.delim' = '|',
  'serialization.format' = '|')