import pandas as pd
import json
import os
import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
from datetime import datetime
import threading
import re
#Generated By AI Start (Cursor)
import traceback
import difflib
import time
#Generated By AI End (Cursor)

# 尝试导入tkinterdnd2，如果没有安装则使用文件选择对话框
try:
    from tkinterdnd2 import DND_FILES, TkinterDnD
    HAS_DND = True
except ImportError:
    HAS_DND = False
    print("提示: 未安装tkinterdnd2，将使用文件选择对话框代替拖放功能")
    print("安装命令: pip install tkinterdnd2")

#Generated By AI Start (Cursor)
KEYWORD_ALIASES = {
    "主题域": ["主题域", "主題域", "主题", "theme", "数据分类"],
    "目标表英文名": ["目标表英文名", "目标表英文名称", "目标英文表名", "目标表名", "英文表名", "目标英文名"],
    "目标表中文名": ["目标表中文名", "目标表中文名称", "目标中文表名", "中文表名", "目标中文名"],
    "数据频度": ["数据频度", "数据频率", "频度", "更新频率"],
    "数据抽取要求": ["数据抽取要求", "抽取要求", "数据抽取"],
    "模型主键": ["模型主键", "主键", "模型主键字段"],
    "来源系统": ["来源系统", "源系统", "数据来源", "来源", "来源系统名称", "源系统名称",
                "源表描述", "源表关联信息描述", "源表基本信息描述", "源表信息描述"],
    "PDM字段英文名": ["PDM字段英文名", "PDM字段英文名称", "字段英文名", "字段英文名称", "PDM英文名"],
    "详细字段信息": ["详细字段信息", "字段说明", "字段信息"],
}

OPTIONAL_HEADER_FIELDS = {"主题域", "数据频度", "模型主键", "目标表中文名", "数据抽取要求"}

FUZZY_THRESHOLD = 0.6
#Generated By AI End (Cursor)

# 从原脚本复制的函数
def convert_to_serializable(obj):
    """
    将不可JSON序列化的对象转换为可序列化的格式
    """
    #Generated By AI Start (Cursor)
    if obj is pd.NaT:
        return None
    try:
        if pd.isna(obj):
            return None
    except (TypeError, ValueError):
        pass
    #Generated By AI End (Cursor)
    if isinstance(obj, datetime):
        return obj.strftime('%Y-%m-%d %H:%M:%S')
    elif isinstance(obj, (pd.Timestamp,)):
        return obj.strftime('%Y-%m-%d %H:%M:%S') if not pd.isna(obj) else None
    else:
        return obj


def toon_escape_value(value):
    """
    对TOON格式的值进行转义处理
    - 如果值包含特殊字符（逗号、换行、冒号等），用双引号包裹
    - 如果值本身包含双引号，进行转义
    """
    if value is None:
        return "null"
    
    value_str = str(value)
    
    #Generated By AI Start (Cursor)
    needs_quotes = any(char in value_str for char in [',', '\n', '\r', ':', '"', '|', '\\'])
    #Generated By AI End (Cursor)
    
    # 检查是否是关键字（避免混淆）
    if value_str.lower() in ['true', 'false', 'null']:
        if not isinstance(value, bool) and value is not None:
            needs_quotes = True
    
    if needs_quotes:
        #Generated By AI Start (Cursor)
        escaped = value_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')
        #Generated By AI End (Cursor)
        return f'"{escaped}"'
    
    return value_str


def convert_to_toon(data):
    """
    将Python字典转换为TOON格式字符串
    TOON (Token-Oriented Object Notation) 是一种为LLM优化的紧凑格式
    """
    lines = []
    
    def format_simple_value(val, indent_level=0):
        """格式化简单值"""
        indent = "  " * indent_level
        if val is None:
            return "null"
        elif isinstance(val, bool):
            return "true" if val else "false"
        elif isinstance(val, (int, float)):
            return str(val)
        else:
            return toon_escape_value(val)
    
    def format_object(obj, indent_level=0):
        """格式化对象（字典）"""
        indent = "  " * indent_level
        result = []
        for key, value in obj.items():
            if value is None:
                result.append(f"{indent}{key}: null")
            elif isinstance(value, bool):
                result.append(f"{indent}{key}: {'true' if value else 'false'}")
            elif isinstance(value, (int, float)):
                result.append(f"{indent}{key}: {value}")
            elif isinstance(value, str):
                result.append(f"{indent}{key}: {toon_escape_value(value)}")
            elif isinstance(value, list):
                # 处理数组
                result.extend(format_array(key, value, indent_level))
            elif isinstance(value, dict):
                result.append(f"{indent}{key}:")
                result.extend(format_object(value, indent_level + 1).split('\n'))
        return '\n'.join(result)
    
    def format_array(key, arr, indent_level=0):
        """格式化数组 - TOON的核心优化"""
        indent = "  " * indent_level
        result = []
        
        if not arr:
            result.append(f"{indent}{key}[0]:")
            return result
        
        # 检查是否是对象数组（结构化数组）
        if all(isinstance(item, dict) for item in arr):
            # 收集所有可能的字段名（保持顺序）
            all_keys = []
            for item in arr:
                for k in item.keys():
                    if k not in all_keys:
                        all_keys.append(k)
            
            # 使用TOON表格格式: key[length]{field1, field2, ...}:
            fields_str = ", ".join(all_keys)
            result.append(f"{indent}{key}[{len(arr)}]{{{fields_str}}}:")
            
            # 每行一条记录
            for item in arr:
                values = []
                for k in all_keys:
                    val = item.get(k)
                    values.append(format_simple_value(val))
                row_indent = "  " * (indent_level + 1)
                result.append(f"{row_indent}{', '.join(values)}")
        else:
            # 简单数组
            simple_values = [format_simple_value(item) for item in arr]
            # 如果值较短，放在一行
            if sum(len(v) for v in simple_values) < 80:
                result.append(f"{indent}{key}[{len(arr)}]: {', '.join(simple_values)}")
            else:
                result.append(f"{indent}{key}[{len(arr)}]:")
                for val in simple_values:
                    row_indent = "  " * (indent_level + 1)
                    result.append(f"{row_indent}{val}")
        
        return result
    
    # 开始格式化顶层对象
    if isinstance(data, dict):
        for key, value in data.items():
            if value is None:
                lines.append(f"{key}: null")
            elif isinstance(value, bool):
                lines.append(f"{key}: {'true' if value else 'false'}")
            elif isinstance(value, (int, float)):
                lines.append(f"{key}: {value}")
            elif isinstance(value, str):
                lines.append(f"{key}: {toon_escape_value(value)}")
            elif isinstance(value, list):
                lines.extend(format_array(key, value, 0))
            elif isinstance(value, dict):
                lines.append(f"{key}:")
                obj_lines = format_object(value, 1)
                lines.extend(obj_lines.split('\n'))
    
    return '\n'.join(lines)

def read_excel_sheets(sheet_names, file_path):
    """
    读取Excel中指定sheet_name列表的数据，返回sheet名与DataFrame的字典
    """
    #Generated By AI Start (Cursor)
    dfs = {}
    xls = pd.ExcelFile(file_path)
    for sheet_name in sheet_names:
        df = xls.parse(sheet_name, header=None)
        dfs[sheet_name] = df
    return dfs
    #Generated By AI End (Cursor)

#Generated By AI Start (Cursor)
def _collect_all_cell_strings(df, max_rows=30):
    """收集DataFrame前N行所有非空单元格的字符串值，用于模糊匹配"""
    cells = []
    for col in df.columns:
        for idx, val in df[col].items():
            if idx >= max_rows:
                break
            s = str(val).strip()
            if s and s != 'nan' and s != 'None':
                cells.append((s, col, idx))
    return cells


def _fuzzy_find_keyword(df, target_str, max_rows=30):
    """
    模糊匹配关键字：先精确匹配别名列表，再用相似度匹配。
    返回 (matched_str, col, idx) 或抛出 ValueError（附带建议）。
    """
    aliases = KEYWORD_ALIASES.get(target_str, [target_str])
    cells = _collect_all_cell_strings(df, max_rows)

    for cell_str, col, idx in cells:
        if cell_str in aliases:
            return cell_str, col, idx

    best_match = None
    best_score = 0.0
    for cell_str, col, idx in cells:
        for alias in aliases:
            score = difflib.SequenceMatcher(None, cell_str, alias).ratio()
            if score > best_score:
                best_score = score
                best_match = (cell_str, col, idx)

    if best_score >= FUZZY_THRESHOLD and best_match:
        return best_match[0], best_match[1], best_match[2]

    candidates = sorted(cells, key=lambda x: max(
        difflib.SequenceMatcher(None, x[0], a).ratio() for a in aliases
    ), reverse=True)[:3]
    hint_strs = [f"'{c[0]}'" for c in candidates]
    hint = f"（相似单元格: {', '.join(hint_strs)}）" if hint_strs else ""
    raise ValueError(f"未在表格内容中找到'{target_str}'！{hint}")
#Generated By AI End (Cursor)

#Generated By AI Start (Cursor)
def _detect_layout(df, target_str):
    """
    检测布局类型并取值。
    Layout A（横向交替）：关键字与值交替排列在同一行
      例如: 主题域 | 专项分析 | 目标表英文名 | dm_xxx_d | 目标表中文名 | xxx
      特征: 关键字右侧紧跟的是非关键字的值
    Layout B（纵向表头）：关键字排列在表头行，值在下一行同列
      例如: 主题域 | 目标表英文名 | 目标表中文名
            PM     | dm_xxx_d    | xxx表
      特征: 关键字右侧紧跟的仍是关键字
    返回 (value, layout_type)
    """
    matched_str, target_col, row_idx = _fuzzy_find_keyword(df, target_str)
    col_list = list(df.columns)
    col_pos = col_list.index(target_col)

    row_data = list(df.loc[row_idx])

    all_known_keywords = set()
    for aliases in KEYWORD_ALIASES.values():
        all_known_keywords.update(aliases)

    right_val = None
    right_str = None
    if col_pos + 1 < len(col_list):
        right_val = row_data[col_pos + 1]
        if not (pd.isna(right_val) or str(right_val).strip() == "" or str(right_val).strip() == "nan"):
            right_str = str(right_val).strip()

    if right_str is not None and right_str not in all_known_keywords:
        return convert_to_serializable(right_val), "A"

    idx_list = list(df.index)
    loc = idx_list.index(row_idx)
    if loc + 1 < len(idx_list):
        next_row_idx = idx_list[loc + 1]
        next_value = df[target_col].loc[next_row_idx]
        return convert_to_serializable(next_value), "B"
    else:
        if right_str is None:
            return None, "A"
        raise ValueError(f"'{target_str}'行已是最后一行，无法获取下方内容！")
#Generated By AI End (Cursor)

def find_next_row_value(df, target_str):
    #Generated By AI Start (Cursor)
    value, _ = _detect_layout(df, target_str)
    return value
    #Generated By AI End (Cursor)

#Generated By AI Start (Cursor)
SOURCE_HEADER_KEYWORDS = [
    "源表英文名", "源表英文名称", "源英文名",
    "源系统", "来源系统", "源表描述", "源表关联信息描述",
]

def _find_source_header_row(df, pdm_row_idx):
    """
    在PDM字段英文名行之前，搜索来源表的真正列表头行。
    列表头行的特征：同一行含有多个列标题（如"源表英文名"、"别名"、"说明"等），至少3个非空单元格。
    节标题行的特征：只有1个非空单元格（如"源表基本信息描述"），应被跳过。
    """
    idx_list = list(df.index)
    pdm_loc = idx_list.index(pdm_row_idx)

    for i in range(pdm_loc - 1, -1, -1):
        row_idx = idx_list[i]
        row = df.loc[row_idx]
        row_list = list(row)
        non_empty = [(j, str(v).strip()) for j, v in enumerate(row_list)
                     if not (pd.isna(v) or str(v).strip() == "" or str(v).strip() == "nan")]
        if len(non_empty) < 2:
            continue
        cell_strs = [s for _, s in non_empty]
        for kw in SOURCE_HEADER_KEYWORDS:
            if any(kw in c for c in cell_strs):
                return row_idx
    raise ValueError("未找到来源表列表头行")
#Generated By AI End (Cursor)

def extract_fields(df):
    #Generated By AI Start (Cursor)
    _, field_col_raw, field_start_idx = _fuzzy_find_keyword(df, 'PDM字段英文名')
    field_col = field_col_raw

    idx_list = list(df.index)
    start_i = idx_list.index(field_start_idx)

    source_table_name_attrs = []
    try:
        source_header_idx = _find_source_header_row(df, field_start_idx)
        source_i = idx_list.index(source_header_idx)

        source_header_row = df.loc[source_header_idx]
        source_header_row_list = list(source_header_row)
        source_col_map = {i: str(val).strip() for i, val in enumerate(source_header_row_list)
                          if not (pd.isna(val) or str(val).strip() == "" or str(val).strip() == "nan")}
        for idx in idx_list[source_i+1 : start_i]:
            row = df.loc[idx]
            row_list = list(row)
            if all(pd.isna(cell) or str(cell).strip() == "" for cell in row_list):
                break
            non_empty_count = sum(1 for cell in row_list if not (pd.isna(cell) or str(cell).strip() == ""))
            if non_empty_count <= 1:
                continue
            attr = {}
            for i, col_name in source_col_map.items():
                if col_name and col_name != 'nan':
                    val = row_list[i] if i < len(row_list) else None
                    if pd.isna(val) or str(val).strip() == "":
                        continue
                    attr[col_name] = convert_to_serializable(val)
            if attr:
                source_table_name_attrs.append(attr)
    except ValueError:
        pass
    #Generated By AI End (Cursor)

    # 分析字段表头
    header_idx = idx_list[start_i]
    header_row = df.loc[header_idx]
    header_row_list = list(header_row)

    # 判断首列是否为空或全空
    if pd.isna(header_row_list[0]) or str(header_row_list[0]).strip() == "":
        col_map = {i: str(val).strip() for i, val in enumerate(header_row_list[1:], start=1)}
        skip_col_indices = [0]
    else:
        col_map = {i: str(val).strip() for i, val in enumerate(header_row_list)}
        skip_col_indices = []

    # 收集字段信息：从header_idx的下一行开始
    fields = []
    for offset in range(start_i + 1, len(idx_list)):
        row_idx = idx_list[offset]
        row = df.loc[row_idx]
        row_list = list(row)
        # 如果这一行全为空，认为到达结尾
        if all([pd.isna(cell) or str(cell).strip() == "" for cell in row_list]):
            break
        field = {}
        for i, col_name in col_map.items():
            if col_name:
                val = row_list[i] if i < len(row_list) else None
                field[col_name] = convert_to_serializable(val)
        fields.append(field)
    return fields, source_table_name_attrs

class ExcelToJsonGUI:
    def __init__(self, root):
        self.root = root
        self.root.title("Excel转TOON工具")
        #Generated By AI Start (Cursor)
        self.root.geometry("850x750")
        #Generated By AI End (Cursor)
        
        self.file_path = None
        self.available_sheets = []  # 所有可用的sheets（原始列表）
        self.filtered_sheets = []    # 筛选后的sheets列表
        self.sheet_checkboxes = {}  # 存储每个sheet的复选框：{sheet_name: (Checkbutton, BooleanVar)}
        self.selected_sheets_set = set()  # 存储所有选中的sheet名称（全局状态，不受筛选影响）
        #Generated By AI Start (Cursor)
        self._processing = False
        #Generated By AI End (Cursor)
        
        self.setup_ui()
        
    def setup_ui(self):
        # 主框架
        main_frame = ttk.Frame(self.root, padding="10")
        main_frame.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        
        # 配置权重
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
        main_frame.columnconfigure(1, weight=1)
        
        # 1. 文件选择区域
        ttk.Label(main_frame, text="1. 选择Excel文件:", font=("Arial", 10, "bold")).grid(row=0, column=0, columnspan=2, sticky=tk.W, pady=(0, 5))
        
        file_frame = ttk.Frame(main_frame)
        file_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=(0, 10))
        file_frame.columnconfigure(1, weight=1)
        
        self.file_label = ttk.Label(file_frame, text="未选择文件", foreground="gray")
        self.file_label.grid(row=0, column=0, columnspan=2, sticky=tk.W, pady=5)
        
        # 拖放区域
        if HAS_DND:
            self.drop_frame = tk.Frame(file_frame, bg="#e0e0e0", relief=tk.SUNKEN, bd=2, height=80)
            self.drop_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
            self.drop_frame.columnconfigure(0, weight=1)
            
            drop_label = tk.Label(
                self.drop_frame, 
                text="拖放Excel文件到这里\n或点击下方按钮选择文件", 
                bg="#e0e0e0",
                font=("Arial", 9),
                justify=tk.CENTER
            )
            drop_label.grid(row=0, column=0, pady=20)
            
            # 绑定拖放事件
            self.drop_frame.drop_target_register(DND_FILES)
            self.drop_frame.dnd_bind('<<Drop>>', self.on_file_drop)
        else:
            # 如果没有tkinterdnd2，只显示文件选择按钮
            self.drop_frame = ttk.Frame(file_frame)
            self.drop_frame.grid(row=1, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=5)
        
        ttk.Button(file_frame, text="选择文件", command=self.select_file).grid(row=2, column=0, padx=5, pady=5)
        
        # 2. Sheet选择区域
        ttk.Label(main_frame, text="2. 选择Sheet:", font=("Arial", 10, "bold")).grid(row=2, column=0, columnspan=2, sticky=tk.W, pady=(10, 5))
        
        sheet_frame = ttk.Frame(main_frame)
        sheet_frame.grid(row=3, column=0, columnspan=2, sticky=(tk.W, tk.E, tk.N, tk.S), pady=(0, 10))
        sheet_frame.columnconfigure(0, weight=1)
        sheet_frame.rowconfigure(1, weight=1)
        
        # 筛选输入框区域
        filter_frame = ttk.Frame(sheet_frame)
        filter_frame.grid(row=0, column=0, sticky=(tk.W, tk.E), pady=(0, 5))
        filter_frame.columnconfigure(0, weight=1)
        
        ttk.Label(filter_frame, text="筛选Sheet:").grid(row=0, column=0, sticky=tk.W, padx=(0, 5))
        self.sheet_filter_entry = ttk.Entry(filter_frame)
        self.sheet_filter_entry.grid(row=0, column=1, sticky=(tk.W, tk.E), padx=(0, 5))
        self.sheet_filter_entry.bind('<KeyRelease>', self.filter_sheets)
        filter_frame.columnconfigure(1, weight=1)
        
        ttk.Label(filter_frame, text="(支持多个关键词，空格分隔)", font=("Arial", 8), foreground="gray").grid(row=1, column=0, columnspan=2, sticky=tk.W, pady=(2, 0))
        
        ttk.Button(filter_frame, text="清除筛选", command=self.clear_filter).grid(row=0, column=2, padx=(5, 0))
        
        # 创建可滚动的复选框区域
        canvas_frame = ttk.Frame(sheet_frame)
        canvas_frame.grid(row=1, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        canvas_frame.columnconfigure(0, weight=1)
        
        canvas_frame.rowconfigure(0, weight=1)
        
        # Canvas用于滚动
        self.sheet_canvas = tk.Canvas(canvas_frame, highlightthickness=0)
        self.sheet_scrollbar = ttk.Scrollbar(canvas_frame, orient="vertical", command=self.sheet_canvas.yview)
        self.sheet_checkbox_frame = ttk.Frame(self.sheet_canvas)
        
        # 将Frame放入Canvas
        self.sheet_canvas_window = self.sheet_canvas.create_window((0, 0), window=self.sheet_checkbox_frame, anchor="nw")
        
        # 配置滚动
        self.sheet_checkbox_frame.bind(
            "<Configure>",
            lambda e: self.sheet_canvas.configure(scrollregion=self.sheet_canvas.bbox("all"))
        )
        self.sheet_canvas.configure(yscrollcommand=self.sheet_scrollbar.set)
        
        # 布局
        self.sheet_canvas.grid(row=0, column=0, sticky=(tk.W, tk.E, tk.N, tk.S))
        self.sheet_scrollbar.grid(row=0, column=1, sticky=(tk.N, tk.S))
        
        # 绑定鼠标滚轮
        def _on_mousewheel(event):
            self.sheet_canvas.yview_scroll(int(-1*(event.delta/120)), "units")
        self.sheet_canvas.bind_all("<MouseWheel>", _on_mousewheel)
        
        # 更新Canvas宽度以匹配Frame
        def configure_canvas_width(event):
            canvas_width = event.width
            self.sheet_canvas.itemconfig(self.sheet_canvas_window, width=canvas_width)
        self.sheet_canvas.bind('<Configure>', configure_canvas_width)
        
        # 按钮区域
        button_frame = ttk.Frame(sheet_frame)
        button_frame.grid(row=2, column=0, pady=5)
        ttk.Button(button_frame, text="全选", command=self.select_all_sheets).grid(row=0, column=0, padx=5)
        ttk.Button(button_frame, text="取消全选", command=self.deselect_all_sheets).grid(row=0, column=1, padx=5)
        
        # 3. 输出目录区域
        ttk.Label(main_frame, text="3. 输出目录:", font=("Arial", 10, "bold")).grid(row=4, column=0, columnspan=2, sticky=tk.W, pady=(10, 5))
        
        output_frame = ttk.Frame(main_frame)
        output_frame.grid(row=5, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=(0, 10))
        output_frame.columnconfigure(0, weight=1)
        
        self.output_entry = ttk.Entry(output_frame)
        self.output_entry.grid(row=0, column=0, sticky=(tk.W, tk.E), padx=(0, 5))
        self.output_entry.insert(0, os.path.join(os.getcwd(), "toon_output"))
        
        ttk.Button(output_frame, text="浏览", command=self.select_output_dir).grid(row=0, column=1)
        
        # 4. 执行按钮
        self.process_button = ttk.Button(main_frame, text="开始转换", command=self.process_files, state=tk.DISABLED)
        self.process_button.grid(row=6, column=0, columnspan=2, pady=(10, 5))

        #Generated By AI Start (Cursor)
        # 5. 进度条区域
        progress_frame = ttk.Frame(main_frame)
        progress_frame.grid(row=7, column=0, columnspan=2, sticky=(tk.W, tk.E), pady=(0, 5))
        progress_frame.columnconfigure(0, weight=1)

        self.progress_bar = ttk.Progressbar(progress_frame, orient="horizontal", mode="determinate")
        self.progress_bar.grid(row=0, column=0, sticky=(tk.W, tk.E), padx=(0, 10))

        self.progress_label = ttk.Label(progress_frame, text="就绪", foreground="gray", width=30, anchor=tk.W)
        self.progress_label.grid(row=0, column=1, sticky=tk.E)

        # 6. 处理结果区域（精简版：只显示汇总和失败明细）
        ttk.Label(main_frame, text="4. 处理结果:", font=("Arial", 10, "bold")).grid(row=8, column=0, columnspan=2, sticky=tk.W, pady=(10, 5))

        self.log_text = scrolledtext.ScrolledText(main_frame, height=15, width=80, font=("Consolas", 9))
        self.log_text.grid(row=9, column=0, columnspan=2, sticky=(tk.W, tk.E, tk.N, tk.S), pady=(0, 10))

        self.log_text.tag_configure("success", foreground="#228B22")
        self.log_text.tag_configure("error", foreground="#CC0000")
        self.log_text.tag_configure("warn", foreground="#CC8800")
        self.log_text.tag_configure("header", foreground="#003399", font=("Consolas", 10, "bold"))
        self.log_text.tag_configure("info", foreground="#555555")

        main_frame.rowconfigure(9, weight=1)
        #Generated By AI End (Cursor)
        
    def on_file_drop(self, event):
        """处理文件拖放事件"""
        files = self.root.tk.splitlist(event.data)
        if files:
            file_path = files[0].strip('{}')  # 移除可能的括号
            if file_path.lower().endswith(('.xlsx', '.xls', '.xlsm')):
                self.load_file(file_path)
            else:
                messagebox.showerror("错误", "请拖放Excel文件（.xlsx、.xls或.xlsm格式）")
    
    def select_file(self):
        """选择文件"""
        file_path = filedialog.askopenfilename(
            title="选择Excel文件",
            #Generated By AI Start (Cursor)
            filetypes=[("Excel文件", "*.xlsx *.xls *.xlsm"), ("所有文件", "*.*")]
            #Generated By AI End (Cursor)
        )
        if file_path:
            self.load_file(file_path)
    
    def load_file(self, file_path):
        """加载Excel文件并读取所有sheet"""
        try:
            self.file_path = file_path
            self.file_label.config(text=f"已选择: {os.path.basename(file_path)}", foreground="green")
            
            # 读取所有sheet名称
            excel_file = pd.ExcelFile(file_path)
            self.available_sheets = excel_file.sheet_names
            self.filtered_sheets = self.available_sheets.copy()
            
            # 清空选中状态（默认全部未选中）
            self.selected_sheets_set.clear()
            
            # 清空筛选输入框
            self.sheet_filter_entry.delete(0, tk.END)
            
            # 更新复选框列表（默认全部未选中）
            self.update_sheet_checkboxes()
            
            # 启用处理按钮
            self.process_button.config(state=tk.NORMAL)
            
            #Generated By AI Start (Cursor)
            self._log_tagged(f"成功加载文件: {os.path.basename(file_path)}", "info")
            self._log_tagged(f"发现 {len(self.available_sheets)} 个Sheet，请勾选后点击[开始转换]", "info")
            self._update_progress(0, 0, "就绪")
            #Generated By AI End (Cursor)
            
        except Exception as e:
            messagebox.showerror("错误", f"加载文件失败: {str(e)}")
    
    def filter_sheets(self, event=None):
        """根据输入框内容筛选Sheet列表（支持多个关键词，空格分隔）"""
        filter_text = self.sheet_filter_entry.get().strip()
        
        # 保存当前选中的状态（从复选框读取）
        self.save_selected_sheets()
        
        if not filter_text:
            # 如果筛选为空，显示所有sheets
            self.filtered_sheets = self.available_sheets.copy()
        else:
            # 支持多个关键词，空格分隔
            keywords = [k.strip().lower() for k in filter_text.split() if k.strip()]
            if keywords:
                # 筛选包含任意关键词的sheets（不区分大小写）
                self.filtered_sheets = [sheet for sheet in self.available_sheets 
                                       if any(keyword in sheet.lower() for keyword in keywords)]
            else:
                self.filtered_sheets = self.available_sheets.copy()
        
        # 更新复选框列表
        self.update_sheet_checkboxes()
        
        # 恢复之前选中的状态
        self.restore_selected_sheets()
    
    def save_selected_sheets(self):
        """保存当前选中的sheets名称（从复选框读取）"""
        for sheet_name in list(self.sheet_checkboxes.keys()):
            checkbox, var = self.sheet_checkboxes[sheet_name]
            if var.get():
                self.selected_sheets_set.add(sheet_name)
            else:
                self.selected_sheets_set.discard(sheet_name)
    
    def restore_selected_sheets(self):
        """恢复之前选中的sheets（设置复选框状态）"""
        for sheet_name in self.filtered_sheets:
            if sheet_name in self.sheet_checkboxes:
                checkbox, var = self.sheet_checkboxes[sheet_name]
                var.set(sheet_name in self.selected_sheets_set)
    
    def update_sheet_checkboxes(self):
        """更新复选框列表显示"""
        # 清除所有现有复选框
        for widget in self.sheet_checkbox_frame.winfo_children():
            widget.destroy()
        self.sheet_checkboxes.clear()
        
        # 为每个筛选后的sheet创建复选框
        for idx, sheet_name in enumerate(self.filtered_sheets):
            var = tk.BooleanVar()
            # 根据全局选中状态设置初始值
            var.set(sheet_name in self.selected_sheets_set)
            
            checkbox = ttk.Checkbutton(
                self.sheet_checkbox_frame,
                text=sheet_name,
                variable=var,
                command=lambda name=sheet_name: self.on_checkbox_changed(name)
            )
            checkbox.grid(row=idx, column=0, sticky=tk.W, padx=5, pady=2)
            
            self.sheet_checkboxes[sheet_name] = (checkbox, var)
        
        # 更新Canvas滚动区域
        self.sheet_checkbox_frame.update_idletasks()
        self.sheet_canvas.configure(scrollregion=self.sheet_canvas.bbox("all"))
    
    def on_checkbox_changed(self, sheet_name):
        """复选框状态改变时的回调"""
        if sheet_name in self.sheet_checkboxes:
            checkbox, var = self.sheet_checkboxes[sheet_name]
            if var.get():
                self.selected_sheets_set.add(sheet_name)
            else:
                self.selected_sheets_set.discard(sheet_name)
    
    def clear_filter(self):
        """清除筛选"""
        self.sheet_filter_entry.delete(0, tk.END)
        self.filter_sheets()
    
    def select_all_sheets(self):
        """全选当前显示的sheet"""
        self.save_selected_sheets()
        for sheet_name in self.filtered_sheets:
            self.selected_sheets_set.add(sheet_name)
        self.restore_selected_sheets()
    
    def deselect_all_sheets(self):
        """取消全选当前显示的sheet"""
        self.save_selected_sheets()
        for sheet_name in self.filtered_sheets:
            self.selected_sheets_set.discard(sheet_name)
        self.restore_selected_sheets()
    
    def select_output_dir(self):
        """选择输出目录"""
        dir_path = filedialog.askdirectory(title="选择输出目录")
        if dir_path:
            self.output_entry.delete(0, tk.END)
            self.output_entry.insert(0, dir_path)

    #Generated By AI Start (Cursor)
    def _log_tagged(self, message, tag=None):
        """带样式标签的日志输出"""
        self.log_text.insert(tk.END, f"{message}\n", tag)
        self.log_text.see(tk.END)
        self.root.update_idletasks()

    def _update_progress(self, current, total, text=None):
        """更新进度条（线程安全）"""
        def _do():
            if total > 0:
                pct = int(current / total * 100)
                self.progress_bar['maximum'] = total
                self.progress_bar['value'] = current
                label = text or f"{current}/{total} ({pct}%)"
            else:
                self.progress_bar['value'] = 0
                label = text or "就绪"
            self.progress_label.config(text=label)
        self.root.after(0, _do)
    #Generated By AI End (Cursor)
    
    def log(self, message):
        """添加日志"""
        self.log_text.insert(tk.END, f"{message}\n")
        self.log_text.see(tk.END)
        self.root.update_idletasks()
    
    def process_files(self):
        """处理文件转换"""
        #Generated By AI Start (Cursor)
        if self._processing:
            return
        #Generated By AI End (Cursor)

        if not self.file_path:
            messagebox.showerror("错误", "请先选择Excel文件")
            return
        
        # 保存当前选中的状态
        self.save_selected_sheets()
        
        # 获取选中的sheet名称（从全局选中集合）
        selected_sheets = list(self.selected_sheets_set)
        
        if not selected_sheets:
            messagebox.showerror("错误", "请至少选择一个Sheet")
            return
        
        output_dir = self.output_entry.get().strip()
        if not output_dir:
            messagebox.showerror("错误", "请填写输出目录")
            return
        
        # 禁用按钮，防止重复点击
        #Generated By AI Start (Cursor)
        self._processing = True
        #Generated By AI End (Cursor)
        self.process_button.config(state=tk.DISABLED)
        self.log_text.delete(1.0, tk.END)
        
        # 在新线程中处理，避免界面卡顿
        thread = threading.Thread(target=self._process_files_thread, args=(selected_sheets, output_dir))
        thread.daemon = True
        thread.start()
    
    def _process_files_thread(self, sheet_names, output_dir):
        """处理文件的线程函数"""
        #Generated By AI Start (Cursor)
        start_time = time.time()
        success_list = []
        error_list = []
        total = len(sheet_names)

        try:
            os.makedirs(output_dir, exist_ok=True)
            self._update_progress(0, total, f"正在加载文件... 0/{total}")

            xls = pd.ExcelFile(self.file_path)

            for i, sheet in enumerate(sheet_names):
                self._update_progress(i, total, f"处理中: {i}/{total} - {sheet}")
                try:
                    df = xls.parse(sheet, header=None)

                    #Generated By AI Start (Cursor)
                    meta_keys = ["主题域", "目标表英文名", "目标表中文名", "数据频度", "模型主键"]
                    meta_vals = {}
                    for mk in meta_keys:
                        try:
                            meta_vals[mk] = find_next_row_value(df, mk)
                        except ValueError:
                            meta_vals[mk] = None
                    theme_domain = meta_vals["主题域"]
                    target_table_name = meta_vals["目标表英文名"]
                    target_table_name_chinese = meta_vals["目标表中文名"]
                    data_frequency = meta_vals["数据频度"]
                    primary_key = meta_vals["模型主键"]

                    if target_table_name is None:
                        raise ValueError("未找到'目标表英文名'，无法确定输出文件名")
                    #Generated By AI End (Cursor)

                    fields, source_table_name_attrs = extract_fields(df)

                    result_json = {
                        "theme_domain": theme_domain,
                        "table_name": target_table_name,
                        "table_name_chinese": target_table_name_chinese,
                        "data_frequency": data_frequency,
                        "primary_key": primary_key,
                        "source_table_name": source_table_name_attrs,
                        "fields": fields
                    }

                    safe_sheet_name = "".join(c if c not in r'\/:*?"<>|' else "_" for c in str(sheet).strip())
                    safe_table_name = "".join(c if c not in r'\/:*?"<>|' else "_" for c in str(target_table_name).strip())
                    table_file_name = f"{safe_sheet_name}_{safe_table_name}.toon"
                    output_path = os.path.join(output_dir, table_file_name)

                    toon_content = convert_to_toon(result_json)
                    with open(output_path, "w", encoding="utf-8") as f:
                        f.write(toon_content)

                    success_list.append({
                        "sheet": sheet,
                        "table": target_table_name,
                        "file": table_file_name,
                        "fields_count": len(fields),
                    })

                except Exception as e:
                    error_list.append({
                        "sheet": sheet,
                        "error": str(e),
                        "traceback": traceback.format_exc(),
                    })

            self._update_progress(total, total, f"完成: {total}/{total}")
            elapsed = time.time() - start_time

            self._show_summary(success_list, error_list, elapsed, output_dir)
            self._generate_report(success_list, error_list, elapsed, output_dir)

        except Exception as e:
            self.root.after(0, lambda msg=str(e): (
                self._log_tagged(f"处理过程出错: {msg}", "error"),
                messagebox.showerror("错误", f"处理过程出错: {msg}")
            ))
        finally:
            self._processing = False
            self.root.after(0, lambda: self.process_button.config(state=tk.NORMAL))

    def _show_summary(self, success_list, error_list, elapsed, output_dir):
        """在结果区域显示精简汇总"""
        def _do():
            self.log_text.delete(1.0, tk.END)

            self._log_tagged("=" * 60, "header")
            self._log_tagged("  处理结果汇总", "header")
            self._log_tagged("=" * 60, "header")
            self._log_tagged("")
            self._log_tagged(f"  文件: {os.path.basename(self.file_path)}", "info")
            self._log_tagged(f"  输出: {output_dir}", "info")
            self._log_tagged(f"  耗时: {elapsed:.1f} 秒", "info")
            self._log_tagged("")
            self._log_tagged(f"  成功: {len(success_list)} 个Sheet", "success")
            self._log_tagged(f"  失败: {len(error_list)} 个Sheet", "error" if error_list else "info")
            self._log_tagged(f"  合计: {len(success_list) + len(error_list)} 个Sheet", "info")
            self._log_tagged("")

            if error_list:
                self._log_tagged("-" * 60)
                self._log_tagged("  失败明细:", "error")
                self._log_tagged("-" * 60)
                for idx, err in enumerate(error_list, 1):
                    self._log_tagged(f"  {idx}. Sheet: [{err['sheet']}]", "error")
                    self._log_tagged(f"     原因: {err['error']}", "warn")
                    self._log_tagged("")

            if success_list:
                self._log_tagged("-" * 60)
                self._log_tagged(f"  成功列表 (共{len(success_list)}个):", "success")
                self._log_tagged("-" * 60)
                for idx, s in enumerate(success_list, 1):
                    self._log_tagged(f"  {idx}. [{s['sheet']}] -> {s['file']} ({s['fields_count']}个字段)", "success")

            self._log_tagged("")
            self._log_tagged("=" * 60)

            report_path = os.path.join(output_dir, "处理报告.md")
            self._log_tagged(f"  详细报告已生成: {report_path}", "info")
            self._log_tagged("=" * 60)

            total = len(success_list) + len(error_list)
            messagebox.showinfo(
                "完成",
                f"处理完成!\n成功: {len(success_list)} 个\n失败: {len(error_list)} 个\n耗时: {elapsed:.1f}秒\n\n详细报告: {report_path}"
            )

        self.root.after(0, _do)

    def _generate_report(self, success_list, error_list, elapsed, output_dir):
        """生成Markdown格式的处理结果报告"""
        lines = []
        lines.append("# Excel转TOON - 处理结果报告")
        lines.append("")
        lines.append(f"**处理时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**源文件**: {os.path.basename(self.file_path)}")
        lines.append(f"**输出目录**: {output_dir}")
        lines.append(f"**处理耗时**: {elapsed:.1f} 秒")
        lines.append("")

        total = len(success_list) + len(error_list)
        rate = len(success_list) / total * 100 if total > 0 else 0
        lines.append("## 处理汇总")
        lines.append("")
        lines.append(f"| 项目 | 数量 |")
        lines.append(f"|------|------|")
        lines.append(f"| 成功 | {len(success_list)} |")
        lines.append(f"| 失败 | {len(error_list)} |")
        lines.append(f"| 合计 | {total} |")
        lines.append(f"| 成功率 | {rate:.1f}% |")
        lines.append("")

        if error_list:
            lines.append("## 失败明细")
            lines.append("")
            lines.append("| 序号 | Sheet名称 | 失败原因 |")
            lines.append("|------|-----------|----------|")
            for idx, err in enumerate(error_list, 1):
                reason = err['error'].replace('\n', ' ').replace('|', '\\|')
                lines.append(f"| {idx} | {err['sheet']} | {reason} |")
            lines.append("")

            lines.append("### 详细堆栈信息")
            lines.append("")
            for idx, err in enumerate(error_list, 1):
                lines.append(f"#### {idx}. Sheet: {err['sheet']}")
                lines.append("")
                lines.append("```")
                lines.append(err['traceback'].strip())
                lines.append("```")
                lines.append("")

        if success_list:
            lines.append("## 成功列表")
            lines.append("")
            lines.append("| 序号 | Sheet名称 | 目标表名 | 输出文件 | 字段数 |")
            lines.append("|------|-----------|----------|----------|--------|")
            for idx, s in enumerate(success_list, 1):
                lines.append(f"| {idx} | {s['sheet']} | {s['table']} | {s['file']} | {s['fields_count']} |")
            lines.append("")

        report_path = os.path.join(output_dir, "处理报告.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
    #Generated By AI End (Cursor)

def main():
    if HAS_DND:
        root = TkinterDnD.Tk()
    else:
        root = tk.Tk()
    
    app = ExcelToJsonGUI(root)
    root.mainloop()

if __name__ == '__main__':
    main()
